### ISSUE TITLE
Support tabs shortcode

### ISSUE THREAD

**Issue by librabyte** [librabyte/hugo-theme-cosmos#7]
reference:
- https://geekdocs.de/shortcodes/tabs/

**Comment by SimpCosm** [comment]
reference: https://github.com/rvanhorn/hugo-dynamic-tabs

**Comment by SimpCosm** [comment]
reference: https://kubernetes.io/docs/contribute/style/hugo-shortcodes/#tabs

**Comment by librabyte** [comment]
supported now!
